version: '3.8'
services:
  sense:
    container_name: sense
    build:
      context: ./sense
    depends_on:
      - influxdb
    env_file:
      - ./.env
  influxdb:
    image: influxdb
    healthcheck:
      test: ["CMD", "curl", "localhost:8086"]
    container_name: influxdb
    ports:
      - 8086:8086
    volumes:
      - ./config:/etc/influxdb2
      - ./db:/var/lib/influxdb2